/**
 * GET /api/video-studio/[id]/shots  — get the shot list
 * PUT /api/video-studio/[id]/shots  — update the shot list
 *
 * Shot list is an array of scene objects generated by Director Mode.
 * Artists can reorder or edit individual scene prompts before generation.
 *
 * Shot list schema (each item):
 * {
 *   index:     number,
 *   prompt:    string,
 *   model:     string,
 *   startTime: number,
 *   endTime:   number,
 *   duration:  number,
 *   type:      string,  // SceneType
 *   energy:    number,  // 0-1
 * }
 */

import { auth }                  from "@/lib/auth";
import { db }                    from "@/lib/db";
import { NextRequest, NextResponse } from "next/server";

export async function GET(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id } = await params;

    const video = await db.musicVideo.findUnique({
      where:  { id },
      select: { id: true, shotList: true, mode: true },
    });

    if (!video) return NextResponse.json({ error: "Not found" }, { status: 404 });

    return NextResponse.json({ shots: video.shotList ?? [] });

  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}

export async function PUT(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  try {
    const { id }   = await params;
    const { shots } = await req.json() as { shots: object[] };
    const session  = await auth();

    if (!Array.isArray(shots)) {
      return NextResponse.json({ error: "shots array required" }, { status: 400 });
    }

    const video = await db.musicVideo.findUnique({
      where:  { id },
      select: { id: true, userId: true, status: true },
    });

    if (!video) return NextResponse.json({ error: "Not found" }, { status: 404 });

    if (video.userId && session?.user?.id !== video.userId) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 403 });
    }

    // Don't allow shot list edits once generation has started
    const frozenStatuses = ["GENERATING", "STITCHING", "COMPLETE"];
    if (frozenStatuses.includes(video.status)) {
      return NextResponse.json({
        error: "Shot list cannot be edited after generation starts",
      }, { status: 400 });
    }

    await db.musicVideo.update({
      where: { id },
      data:  { shotList: shots },
    });

    return NextResponse.json({ shots });

  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: msg }, { status: 500 });
  }
}
