/**
 * GET /api/dashboard/ai/track-shield/[scanId]/pdf
 * Downloads a plain-text report for the scan (no extra dependencies needed).
 */

import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth";
import { db } from "@/lib/db";

interface MatchEntry {
  platform:   string;
  url:        string | null;
  uploader:   string;
  confidence: number;
  foundAt:    string;
  title:      string;
  artist:     string;
  album:      string;
}

export async function GET(
  _req: NextRequest,
  { params }: { params: Promise<{ scanId: string }> }
) {
  const session = await auth();
  if (!session?.user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const { scanId } = await params;

  const scan = await db.trackShieldScan.findFirst({
    where: { id: scanId, userId: session.user.id },
    include: {
      tracks: {
        include: {
          track: { select: { id: true, title: true } },
        },
      },
    },
  });

  if (!scan) {
    return NextResponse.json({ error: "Scan not found" }, { status: 404 });
  }

  const PACKAGE_LABELS: Record<string, string> = {
    SINGLE:  "Single Track",
    PACK_5:  "5-Track Pack",
    PACK_10: "10-Track Pack",
    CATALOG: "Full Catalog",
  };

  const lines: string[] = [
    "TRACK SHIELD SCAN REPORT",
    "========================",
    `Scan ID:  ${scan.id}`,
    `Date:     ${scan.createdAt.toISOString()}`,
    `Package:  ${PACKAGE_LABELS[scan.packageType] ?? scan.packageType}`,
    `Status:   ${scan.status}`,
    "",
    "RESULTS",
    "-------",
  ];

  for (const result of scan.tracks) {
    lines.push(`Track: ${result.track.title}`);
    lines.push(`Matches Found: ${result.matchCount}`);

    const matches = Array.isArray(result.matches)
      ? (result.matches as unknown as MatchEntry[])
      : [];

    if (matches.length === 0) {
      lines.push("  No matches found.");
    } else {
      for (const m of matches) {
        lines.push(`  - Platform:          ${m.platform}`);
        lines.push(`    Title:             ${m.title}`);
        lines.push(`    Artist:            ${m.artist}`);
        lines.push(`    Album:             ${m.album}`);
        if (m.url) {
          lines.push(`    URL:               ${m.url}`);
        }
        lines.push(`    Match Confidence:  ${m.confidence}%`);
        lines.push(`    Found:             ${m.foundAt}`);
      }
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("Generated by Track Shield — IndieThis");

  const content = lines.join("\n");
  const filename = `track-shield-${scan.id}.txt`;

  return new NextResponse(content, {
    headers: {
      "Content-Type":        "text/plain; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
