import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const PRESETS = [
  {
    name:        "Dark Trap",
    genre:       "HIP_HOP",
    description: "Heavy 808 bass, aggressive drum compression, dark vocal treatment, sub-heavy mix",
    sortOrder:   0,
    mixProfile: {
      vocals: {
        highpass:    100,
        eq:          [{ type: "highshelf", freq: 8000, gain: -2 }, { type: "presence", freq: 3000, gain: 1.5 }],
        compression: { threshold: -18, ratio: 4, attack: 5, release: 80 },
        reverb:      { roomSize: 0.55, mix: 0.28, damping: 0.7 },
        delay:       { time: 0.375, feedback: 0.3, mix: 0.18 },
        saturation:  1.5,
        gain:        0,
        pan:         0,
        noiseGate:   { threshold: -55, release: 200 },
      },
      bass: {
        highpass:    30,
        eq:          [{ type: "boost", freq: 60, gain: 3 }, { type: "cut", freq: 250, gain: -2 }],
        compression: { threshold: -12, ratio: 6, attack: 8, release: 120 },
        saturation:  2.5,
        gain:        1,
        pan:         0,
        monoBelow:   200,
      },
      drums: {
        highpass:    40,
        eq:          [{ type: "boost", freq: 80, gain: 2 }, { type: "boost", freq: 5000, gain: 1.5 }],
        compression: { threshold: -14, ratio: 5, attack: 2, release: 60 },
        saturation:  3,
        gain:        0.5,
        pan:         0,
      },
      guitar: {
        highpass:    120,
        eq:          [{ type: "cut", freq: 400, gain: -1.5 }],
        compression: { threshold: -20, ratio: 3, attack: 15, release: 100 },
        reverb:      { roomSize: 0.3, mix: 0.15, damping: 0.5 },
        saturation:  1,
        gain:        -1,
        pan:         0.3,
      },
      keys: {
        highpass:    80,
        eq:          [{ type: "cut", freq: 300, gain: -2 }],
        compression: { threshold: -22, ratio: 3, attack: 20, release: 150 },
        reverb:      { roomSize: 0.45, mix: 0.22, damping: 0.6 },
        saturation:  0.5,
        gain:        -2,
        pan:         -0.25,
      },
      pad: {
        highpass:    120,
        compression: { threshold: -24, ratio: 2.5, attack: 30, release: 200 },
        reverb:      { roomSize: 0.7, mix: 0.4, damping: 0.4 },
        gain:        -4,
        pan:         0,
      },
      fx: {
        compression: { threshold: -24, ratio: 2, attack: 10, release: 150 },
        reverb:      { roomSize: 0.8, mix: 0.5, damping: 0.3 },
        gain:        -3,
        pan:         0,
      },
      other: {
        highpass:    80,
        compression: { threshold: -22, ratio: 3, attack: 20, release: 120 },
        gain:        -2,
        pan:         0,
      },
    },
    masterProfile: {
      targetLufs:    [-8, -9, -10, -10],  // Clean, Warm, Punch, Loud
      eq:            [{ type: "boost", freq: 55, gain: 1.5 }, { type: "cut", freq: 300, gain: -1 }],
      multibandCompression: [
        { low: 20,   high: 120,  threshold: -10, ratio: 3,   attack: 10,  release: 150, makeupGain: 1 },
        { low: 120,  high: 800,  threshold: -14, ratio: 2.5, attack: 15,  release: 120, makeupGain: 0.5 },
        { low: 800,  high: 5000, threshold: -16, ratio: 2,   attack: 20,  release: 100, makeupGain: 0 },
        { low: 5000, high: 20000,threshold: -18, ratio: 1.5, attack: 30,  release: 80,  makeupGain: -0.5 },
      ],
      stereoWidth:   1.1,
      monoBelow:     150,
      saturation:    1.5,
      limiterThreshold: -0.5,
      limiterRelease:   80,
    },
  },

  {
    name:        "Bright Pop",
    genre:       "POP",
    description: "Clear vocals forward, wide stereo image, bright highs, moderate compression",
    sortOrder:   1,
    mixProfile: {
      vocals: {
        highpass:    100,
        eq:          [{ type: "presence", freq: 4000, gain: 2 }, { type: "air", freq: 12000, gain: 1.5 }],
        compression: { threshold: -16, ratio: 3, attack: 8, release: 100 },
        reverb:      { roomSize: 0.4, mix: 0.22, damping: 0.5 },
        delay:       { time: 0.25, feedback: 0.2, mix: 0.12 },
        saturation:  0.5,
        gain:        1,
        pan:         0,
        noiseGate:   { threshold: -60, release: 200 },
      },
      bass: {
        highpass:    40,
        eq:          [{ type: "boost", freq: 80, gain: 1.5 }, { type: "cut", freq: 200, gain: -1 }],
        compression: { threshold: -14, ratio: 4, attack: 10, release: 100 },
        saturation:  1,
        gain:        0,
        pan:         0,
        monoBelow:   200,
      },
      drums: {
        highpass:    50,
        eq:          [{ type: "boost", freq: 8000, gain: 2 }],
        compression: { threshold: -16, ratio: 4, attack: 3, release: 60 },
        saturation:  1.5,
        gain:        0,
        pan:         0,
      },
      guitar: {
        highpass:    100,
        eq:          [{ type: "boost", freq: 3000, gain: 1 }],
        compression: { threshold: -18, ratio: 2.5, attack: 20, release: 120 },
        reverb:      { roomSize: 0.35, mix: 0.18, damping: 0.5 },
        saturation:  0.5,
        gain:        -1,
        pan:         0.4,
      },
      keys: {
        highpass:    60,
        eq:          [{ type: "boost", freq: 6000, gain: 1 }],
        compression: { threshold: -20, ratio: 2.5, attack: 25, release: 150 },
        reverb:      { roomSize: 0.45, mix: 0.25, damping: 0.4 },
        saturation:  0,
        gain:        -1,
        pan:         -0.3,
      },
      pad: {
        highpass:    100,
        compression: { threshold: -24, ratio: 2, attack: 40, release: 250 },
        reverb:      { roomSize: 0.65, mix: 0.38, damping: 0.35 },
        gain:        -3,
        pan:         0,
      },
      fx:    { compression: { threshold: -24, ratio: 2, attack: 10, release: 150 }, reverb: { roomSize: 0.7, mix: 0.45, damping: 0.3 }, gain: -4, pan: 0 },
      other: { highpass: 80, compression: { threshold: -22, ratio: 2.5, attack: 20, release: 120 }, gain: -2, pan: 0 },
    },
    masterProfile: {
      targetLufs:    [-12, -13, -11, -10],
      eq:            [{ type: "boost", freq: 10000, gain: 1 }, { type: "cut", freq: 400, gain: -0.5 }],
      multibandCompression: [
        { low: 20,   high: 120,  threshold: -14, ratio: 2.5, attack: 15,  release: 150, makeupGain: 0.5 },
        { low: 120,  high: 800,  threshold: -16, ratio: 2,   attack: 20,  release: 120, makeupGain: 0 },
        { low: 800,  high: 5000, threshold: -16, ratio: 2,   attack: 20,  release: 100, makeupGain: 0.5 },
        { low: 5000, high: 20000,threshold: -18, ratio: 1.5, attack: 30,  release: 80,  makeupGain: 1 },
      ],
      stereoWidth:   1.25,
      monoBelow:     120,
      saturation:    0.5,
      limiterThreshold: -0.8,
      limiterRelease:   100,
    },
  },

  {
    name:        "R&B Smooth",
    genre:       "RNB",
    description: "Warm low-mids, silky vocal presence, gentle compression, wide pad stereo",
    sortOrder:   2,
    mixProfile: {
      vocals: {
        highpass:    90,
        eq:          [{ type: "warmth", freq: 200, gain: 1 }, { type: "presence", freq: 3500, gain: 1.5 }, { type: "air", freq: 10000, gain: 1 }],
        compression: { threshold: -18, ratio: 2.5, attack: 10, release: 120 },
        reverb:      { roomSize: 0.5, mix: 0.3, damping: 0.45 },
        delay:       { time: 0.375, feedback: 0.25, mix: 0.15 },
        saturation:  0.8,
        gain:        1,
        pan:         0,
        noiseGate:   { threshold: -58, release: 200 },
      },
      bass: {
        highpass:    35,
        eq:          [{ type: "boost", freq: 70, gain: 1 }, { type: "boost", freq: 180, gain: 1.5 }],
        compression: { threshold: -16, ratio: 4, attack: 12, release: 100 },
        saturation:  1.5,
        gain:        0.5,
        pan:         0,
        monoBelow:   200,
      },
      drums: {
        highpass:    50,
        eq:          [{ type: "warmth", freq: 150, gain: 1 }],
        compression: { threshold: -18, ratio: 3.5, attack: 5, release: 80 },
        saturation:  1,
        gain:        -0.5,
        pan:         0,
      },
      guitar: {
        highpass:    100,
        compression: { threshold: -20, ratio: 2.5, attack: 20, release: 120 },
        reverb:      { roomSize: 0.4, mix: 0.2, damping: 0.5 },
        saturation:  0.5,
        gain:        -2,
        pan:         0.35,
      },
      keys: {
        highpass:    60,
        eq:          [{ type: "warmth", freq: 250, gain: 1 }],
        compression: { threshold: -22, ratio: 2, attack: 30, release: 180 },
        reverb:      { roomSize: 0.55, mix: 0.3, damping: 0.4 },
        saturation:  0.3,
        gain:        -1.5,
        pan:         -0.3,
      },
      pad: {
        highpass:    80,
        compression: { threshold: -26, ratio: 2, attack: 50, release: 300 },
        reverb:      { roomSize: 0.75, mix: 0.45, damping: 0.3 },
        gain:        -2,
        pan:         0,
      },
      fx:    { compression: { threshold: -26, ratio: 1.5, attack: 10, release: 200 }, reverb: { roomSize: 0.8, mix: 0.5, damping: 0.3 }, gain: -4, pan: 0 },
      other: { highpass: 80, compression: { threshold: -22, ratio: 2.5, attack: 20, release: 150 }, gain: -2, pan: 0 },
    },
    masterProfile: {
      targetLufs:    [-12, -12, -11, -10],
      eq:            [{ type: "warmth", freq: 200, gain: 0.8 }, { type: "boost", freq: 8000, gain: 0.5 }],
      multibandCompression: [
        { low: 20,   high: 120,  threshold: -14, ratio: 2.5, attack: 12,  release: 140, makeupGain: 0.5 },
        { low: 120,  high: 800,  threshold: -14, ratio: 2,   attack: 18,  release: 120, makeupGain: 1 },
        { low: 800,  high: 5000, threshold: -16, ratio: 2,   attack: 22,  release: 100, makeupGain: 0.5 },
        { low: 5000, high: 20000,threshold: -18, ratio: 1.5, attack: 28,  release: 90,  makeupGain: 0 },
      ],
      stereoWidth:   1.2,
      monoBelow:     130,
      saturation:    0.8,
      limiterThreshold: -0.8,
      limiterRelease:   120,
    },
  },

  {
    name:        "Lo-Fi Chill",
    genre:       "INDIE",
    description: "Rolled-off highs, tape saturation, vinyl warmth, loose compression",
    sortOrder:   3,
    mixProfile: {
      vocals: {
        highpass:    120,
        eq:          [{ type: "cut", freq: 8000, gain: -3 }, { type: "warmth", freq: 300, gain: 2 }],
        compression: { threshold: -20, ratio: 2, attack: 25, release: 200 },
        reverb:      { roomSize: 0.65, mix: 0.4, damping: 0.6 },
        delay:       { time: 0.5, feedback: 0.35, mix: 0.2 },
        saturation:  4,
        gain:        -1,
        pan:         0,
        noiseGate:   { threshold: -65, release: 300 },
      },
      bass: {
        highpass:    40,
        eq:          [{ type: "warmth", freq: 150, gain: 2 }, { type: "cut", freq: 3000, gain: -3 }],
        compression: { threshold: -18, ratio: 3, attack: 20, release: 150 },
        saturation:  5,
        gain:        1,
        pan:         0,
        monoBelow:   250,
      },
      drums: {
        highpass:    60,
        eq:          [{ type: "cut", freq: 10000, gain: -4 }, { type: "warmth", freq: 200, gain: 2 }],
        compression: { threshold: -22, ratio: 3, attack: 10, release: 100 },
        saturation:  6,
        gain:        -1,
        pan:         0,
      },
      guitar: {
        highpass:    150,
        eq:          [{ type: "cut", freq: 8000, gain: -2 }],
        compression: { threshold: -22, ratio: 2, attack: 30, release: 200 },
        reverb:      { roomSize: 0.5, mix: 0.3, damping: 0.7 },
        saturation:  3,
        gain:        -1.5,
        pan:         0.35,
      },
      keys: {
        highpass:    100,
        eq:          [{ type: "cut", freq: 8000, gain: -3 }],
        compression: { threshold: -24, ratio: 2, attack: 40, release: 250 },
        reverb:      { roomSize: 0.6, mix: 0.35, damping: 0.6 },
        saturation:  2.5,
        gain:        -2,
        pan:         -0.3,
      },
      pad: {
        highpass:    120,
        eq:          [{ type: "cut", freq: 10000, gain: -4 }],
        compression: { threshold: -26, ratio: 2, attack: 60, release: 350 },
        reverb:      { roomSize: 0.8, mix: 0.5, damping: 0.5 },
        saturation:  2,
        gain:        -3,
        pan:         0,
      },
      fx:    { compression: { threshold: -28, ratio: 1.5, attack: 15, release: 200 }, reverb: { roomSize: 0.85, mix: 0.55, damping: 0.5 }, gain: -5, pan: 0 },
      other: { highpass: 100, eq: [{ type: "cut", freq: 8000, gain: -3 }], compression: { threshold: -24, ratio: 2, attack: 25, release: 150 }, saturation: 3, gain: -2, pan: 0 },
    },
    masterProfile: {
      targetLufs:    [-14, -14, -13, -12],
      eq:            [{ type: "cut", freq: 12000, gain: -2 }, { type: "warmth", freq: 200, gain: 1.5 }],
      multibandCompression: [
        { low: 20,   high: 120,  threshold: -16, ratio: 2, attack: 20, release: 200, makeupGain: 1 },
        { low: 120,  high: 800,  threshold: -16, ratio: 2, attack: 25, release: 180, makeupGain: 1 },
        { low: 800,  high: 5000, threshold: -18, ratio: 2, attack: 30, release: 150, makeupGain: 0 },
        { low: 5000, high: 20000,threshold: -20, ratio: 2, attack: 40, release: 120, makeupGain: -1 },
      ],
      stereoWidth:   1.0,
      monoBelow:     200,
      saturation:    5,
      limiterThreshold: -1.0,
      limiterRelease:   150,
    },
  },

  {
    name:        "Hip-Hop Clean",
    genre:       "HIP_HOP",
    description: "Punchy drums, clear vocal presence, tight bass, moderate width",
    sortOrder:   4,
    mixProfile: {
      vocals: {
        highpass:    100,
        eq:          [{ type: "presence", freq: 3500, gain: 2 }, { type: "air", freq: 10000, gain: 1 }],
        compression: { threshold: -16, ratio: 3.5, attack: 6, release: 80 },
        reverb:      { roomSize: 0.35, mix: 0.18, damping: 0.55 },
        delay:       { time: 0.25, feedback: 0.22, mix: 0.12 },
        saturation:  0.8,
        gain:        1.5,
        pan:         0,
        noiseGate:   { threshold: -55, release: 180 },
      },
      bass: {
        highpass:    35,
        eq:          [{ type: "boost", freq: 65, gain: 2 }, { type: "boost", freq: 180, gain: 1 }, { type: "cut", freq: 350, gain: -2 }],
        compression: { threshold: -12, ratio: 5, attack: 8, release: 100 },
        saturation:  2,
        gain:        0.5,
        pan:         0,
        monoBelow:   200,
      },
      drums: {
        highpass:    45,
        eq:          [{ type: "boost", freq: 80, gain: 2.5 }, { type: "boost", freq: 5000, gain: 2 }],
        compression: { threshold: -14, ratio: 5, attack: 2, release: 50 },
        saturation:  2.5,
        gain:        1,
        pan:         0,
      },
      guitar: {
        highpass:    120,
        compression: { threshold: -20, ratio: 3, attack: 18, release: 110 },
        reverb:      { roomSize: 0.3, mix: 0.15, damping: 0.55 },
        saturation:  1,
        gain:        -1.5,
        pan:         0.35,
      },
      keys: {
        highpass:    80,
        compression: { threshold: -22, ratio: 2.5, attack: 22, release: 140 },
        reverb:      { roomSize: 0.4, mix: 0.2, damping: 0.5 },
        saturation:  0.3,
        gain:        -2,
        pan:         -0.3,
      },
      pad: {
        highpass:    100,
        compression: { threshold: -24, ratio: 2, attack: 35, release: 220 },
        reverb:      { roomSize: 0.6, mix: 0.35, damping: 0.45 },
        gain:        -3,
        pan:         0,
      },
      fx:    { compression: { threshold: -24, ratio: 2, attack: 10, release: 150 }, reverb: { roomSize: 0.75, mix: 0.45, damping: 0.35 }, gain: -4, pan: 0 },
      other: { highpass: 80, compression: { threshold: -22, ratio: 3, attack: 20, release: 120 }, gain: -2, pan: 0 },
    },
    masterProfile: {
      targetLufs:    [-10, -11, -10, -9],
      eq:            [{ type: "boost", freq: 70, gain: 1 }, { type: "boost", freq: 5000, gain: 0.8 }, { type: "cut", freq: 300, gain: -0.8 }],
      multibandCompression: [
        { low: 20,   high: 120,  threshold: -12, ratio: 3,   attack: 10,  release: 130, makeupGain: 1 },
        { low: 120,  high: 800,  threshold: -14, ratio: 2.5, attack: 15,  release: 110, makeupGain: 0 },
        { low: 800,  high: 5000, threshold: -16, ratio: 2,   attack: 20,  release: 100, makeupGain: 1 },
        { low: 5000, high: 20000,threshold: -18, ratio: 1.5, attack: 28,  release: 85,  makeupGain: 0 },
      ],
      stereoWidth:   1.1,
      monoBelow:     150,
      saturation:    1,
      limiterThreshold: -0.5,
      limiterRelease:   90,
    },
  },

  {
    name:        "Electronic / EDM",
    genre:       "ELECTRONIC",
    description: "Wide stereo, heavy sidechain compression feel, bright and loud, sub bass mono",
    sortOrder:   5,
    mixProfile: {
      vocals: {
        highpass:    120,
        eq:          [{ type: "cut", freq: 300, gain: -2 }, { type: "presence", freq: 4000, gain: 2.5 }, { type: "air", freq: 12000, gain: 2 }],
        compression: { threshold: -14, ratio: 4, attack: 4, release: 60 },
        reverb:      { roomSize: 0.5, mix: 0.25, damping: 0.45 },
        delay:       { time: 0.125, feedback: 0.35, mix: 0.2 },
        saturation:  1,
        gain:        1,
        pan:         0,
        noiseGate:   { threshold: -55, release: 150 },
      },
      bass: {
        highpass:    30,
        eq:          [{ type: "boost", freq: 55, gain: 3 }, { type: "cut", freq: 250, gain: -3 }],
        compression: { threshold: -10, ratio: 6, attack: 5, release: 80 },
        saturation:  2,
        gain:        1,
        pan:         0,
        monoBelow:   250,
      },
      drums: {
        highpass:    40,
        eq:          [{ type: "boost", freq: 8000, gain: 2.5 }, { type: "boost", freq: 60, gain: 2 }],
        compression: { threshold: -12, ratio: 6, attack: 1, release: 40 },
        saturation:  2,
        gain:        1,
        pan:         0,
      },
      guitar: {
        highpass:    200,
        compression: { threshold: -18, ratio: 3, attack: 15, release: 100 },
        reverb:      { roomSize: 0.55, mix: 0.3, damping: 0.4 },
        saturation:  1.5,
        gain:        -2,
        pan:         0.4,
      },
      keys: {
        highpass:    60,
        eq:          [{ type: "boost", freq: 8000, gain: 1.5 }],
        compression: { threshold: -18, ratio: 3, attack: 15, release: 100 },
        reverb:      { roomSize: 0.6, mix: 0.3, damping: 0.35 },
        saturation:  1,
        gain:        -1,
        pan:         0.3,
      },
      pad: {
        highpass:    80,
        compression: { threshold: -22, ratio: 2, attack: 30, release: 200 },
        reverb:      { roomSize: 0.8, mix: 0.5, damping: 0.25 },
        gain:        -2,
        pan:         0,
      },
      fx:    { compression: { threshold: -22, ratio: 2, attack: 5, release: 100 }, reverb: { roomSize: 0.85, mix: 0.55, damping: 0.2 }, gain: -3, pan: 0 },
      other: { highpass: 80, compression: { threshold: -20, ratio: 3, attack: 15, release: 100 }, gain: -2, pan: 0 },
    },
    masterProfile: {
      targetLufs:    [-8, -9, -8, -7],
      eq:            [{ type: "boost", freq: 55, gain: 2 }, { type: "boost", freq: 12000, gain: 1.5 }, { type: "cut", freq: 300, gain: -1 }],
      multibandCompression: [
        { low: 20,   high: 120,  threshold: -10, ratio: 3.5, attack: 8,   release: 120, makeupGain: 2 },
        { low: 120,  high: 800,  threshold: -14, ratio: 2.5, attack: 12,  release: 100, makeupGain: 0 },
        { low: 800,  high: 5000, threshold: -14, ratio: 2.5, attack: 15,  release: 90,  makeupGain: 1 },
        { low: 5000, high: 20000,threshold: -16, ratio: 2,   attack: 22,  release: 75,  makeupGain: 1.5 },
      ],
      stereoWidth:   1.4,
      monoBelow:     200,
      saturation:    1.5,
      limiterThreshold: -0.3,
      limiterRelease:   60,
    },
  },
];

async function main() {
  console.log("Seeding MasteringPresets…");

  for (const preset of PRESETS) {
    await prisma.masteringPreset.upsert({
      where:  { name: preset.name },
      update: preset,
      create: preset,
    });
    console.log(`  ✓ ${preset.name}`);
  }

  console.log("Done.");
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
