import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — IndieThis",
  description: "IndieThis Terms of Service. Read our terms before using the platform.",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: 36 }}>
      <h2 style={{ fontSize: 16, fontWeight: 600, color: "#fff", marginBottom: 10 }}>{title}</h2>
      <div style={{ fontSize: 14, color: "#aaa", lineHeight: 1.75 }}>{children}</div>
    </div>
  );
}

export default function TermsPage() {
  return (
    <div style={{ backgroundColor: "#0A0A0A", minHeight: "100vh", color: "#e5e5e5" }}>
      {/* Nav */}
      <header
        style={{
          borderBottom: "1px solid rgba(255,255,255,0.06)",
          padding: "16px 24px",
          display: "flex",
          alignItems: "center",
          justifyContent: "space-between",
        }}
      >
        <Link href="/" style={{ textDecoration: "none" }}>
          {/* eslint-disable-next-line @next/next/no-img-element */}
          <img src="/images/brand/indiethis-logo-dark-bg.svg" alt="IndieThis" style={{ height: 32 }} />
        </Link>
        <Link href="/" style={{ fontSize: 13, color: "#888", textDecoration: "none" }}>
          ← Back to home
        </Link>
      </header>

      {/* Content */}
      <main style={{ maxWidth: 760, margin: "0 auto", padding: "56px 24px 80px" }}>
        <p style={{ fontSize: 12, color: "#555", marginBottom: 8, textTransform: "uppercase", letterSpacing: "0.08em" }}>
          Legal
        </p>
        <h1 style={{ fontSize: 36, fontWeight: 700, color: "#fff", marginBottom: 8, lineHeight: 1.15 }}>
          Terms of Service
        </h1>
        <p style={{ fontSize: 13, color: "#555", marginBottom: 48 }}>
          Last Updated: April 2026
        </p>

        <Section title="1. Agreement to Terms">
          By creating an account, subscribing to a plan, or using any feature on IndieThis ("the Platform"), you agree to these Terms of Service. If you do not agree, do not use the Platform. IndieThis is operated by Clear Ear Corp ("we", "us", "our"). These terms apply to all users including artists, producers, studios, and DJs.
        </Section>

        <Section title="2. Accounts and Eligibility">
          You must be at least 18 years old to create an account. You are responsible for maintaining the security of your account credentials. You may not share your account with others. You may sign up using email and password, or through Google or Facebook authentication. One person may hold one account. Creating multiple accounts to manipulate platform features, inflate play counts, or game the Impact Score system is prohibited and grounds for immediate termination.
        </Section>

        <Section title="3. Subscription Plans and Billing">
          IndieThis offers monthly subscription plans for artists, producers, and studios. Prices are listed on the pricing page and may change with 30 days notice. Subscriptions are billed monthly through Stripe. You may cancel at any time through the billing portal — your access continues through the end of the current billing period. No refunds are issued for partial months. Promotional and comp accounts may be granted at our discretion with limited or no access to AI tools, email blasts, and SMS broadcasts.
        </Section>

        <Section title="4. Pay Per Use (PPU) Purchases">
          Certain AI tools and features are available as one-time purchases. PPU charges are non-refundable once processing has begun. If an AI tool fails to produce a result due to a system error, the charge will be refunded or credited to your account. Prices for PPU features are set in the Platform Pricing system and may be adjusted at any time.
        </Section>

        <Section title="5. AI-Generated Content">
          IndieThis provides AI-powered tools including but not limited to cover art generation, music video generation, audio mastering, lyric video creation, vocal removal, bio generation, press kit creation, contract scanning, and A&R reports. AI-generated content is provided "as-is." We do not guarantee that AI output will be free of errors, suitable for any particular purpose, or free of intellectual property conflicts. You are solely responsible for reviewing and using AI-generated content. You own the output generated by AI tools using your inputs, subject to any third-party rights in the underlying AI models. We do not claim ownership of your AI-generated content.
        </Section>

        <Section title="6. User Content and Intellectual Property">
          You retain ownership of all content you upload to IndieThis including music, artwork, videos, bios, and merch designs. By uploading content, you grant IndieThis a non-exclusive, worldwide license to display, distribute, and promote your content within the Platform and in marketing materials for the Platform. This license terminates when you delete your content or close your account, except for content that has been purchased by other users or is part of completed transactions.
          <br /><br />
          You represent that you have all necessary rights to the content you upload. You may not upload content that infringes on any third party&apos;s intellectual property, contains unauthorized samples, or violates any law. IndieThis uses content moderation systems to scan uploaded content for potential violations. Content flagged for violations may be unpublished or removed at our discretion.
        </Section>

        <Section title="7. Music Distribution and Sales">
          Artists may sell digital products (singles, EPs, albums, sample packs) through the Platform. IndieThis retains a 10% platform fee on digital music sales and sample pack sales. Artists set their own prices within the allowed ranges. Buyers receive download access via tokenized links. Downloaded files include ID3 metadata tags. All sales are final — IndieThis does not process refunds for digital content on behalf of artists.
        </Section>

        <Section title="8. Beat Marketplace and Licensing">
          Producers may list beats for licensing on the Platform. Licensing terms (Basic, Exclusive, Unlimited) are defined by the producer. IndieThis facilitates the transaction and generates license documents. Stream leases are billed monthly at the rate set by the producer with a 70/30 revenue split (producer/platform). Failed stream lease payments are subject to a 3-day grace period before the lease is suspended.
        </Section>

        <Section title="9. Merchandise">
          IndieThis offers merchandise sales through two fulfillment methods: print-on-demand via Printful and self-fulfilled by the artist. IndieThis retains 15% of merchandise profit on POD items and 15% of the total product price on self-fulfilled items. For POD products, custom printed items are made to order and cannot be returned unless defective. Defective items will be replaced at no cost through our fulfillment partner. For self-fulfilled products, the artist&apos;s return policy applies. IndieThis does not process merch returns or refunds — these are handled between the buyer and the artist or fulfillment provider.
        </Section>

        <Section title="10. Fan Funding and Platform Credits">
          Fans may support artists by purchasing platform credits. Credits are purchased in US dollars at a 1:1 ratio ($1 = 1 credit). Credits are applied to the artist&apos;s IndieThis balance and can only be spent on Platform services including subscriptions, PPU tools, and merch production costs. Credits cannot be withdrawn as cash, transferred to another user, or converted to any currency. Credits have no expiration date. Fan funding purchases are non-refundable.
        </Section>

        <Section title="11. DJ Platform and Attribution">
          Users may activate DJ mode on their accounts. DJs may create crates, upload mixes, list events, and apply for verification. The DJ Attribution Engine tracks fan discovery through DJ activity and allocates 10% of the artist&apos;s portion on qualifying sales to the attributing DJ. Artists opt into DJ discovery attribution through their settings. The attribution percentage is fixed and cannot be modified by artists or DJs. DJ earnings accumulate in the DJ&apos;s balance and are paid out via Stripe Connect with a $25 minimum withdrawal.
        </Section>

        <Section title="12. Studio Features">
          Studios may use IndieThis for booking management, client CRM, invoicing, file delivery, email campaigns, and intake forms. Intake deposits collected through the Platform are processed via Stripe. Alternative payment methods (Cash App, Zelle) are facilitated through the Platform but processed outside of Stripe — IndieThis is not responsible for verifying external payments. Studios are responsible for their own client relationships, service delivery, and dispute resolution.
        </Section>

        <Section title="13. Platform Agents">
          IndieThis operates automated agents that analyze platform data and take actions including sending emails, notifications, scoring leads, moderating content, and surfacing recommendations. These agents operate on scheduled intervals and event triggers. Agent-generated communications are sent on behalf of IndieThis, not on behalf of individual users. You may not rely on agent recommendations as professional advice — they are informational suggestions based on platform data.
        </Section>

        <Section title="14. Track Shield and Content Scanning">
          Track Shield scans the internet for potential unauthorized use of your music using third-party content recognition services. Results are informational and do not constitute legal evidence of infringement. IndieThis does not provide legal advice or take enforcement action on your behalf. You are responsible for pursuing any claims of infringement through appropriate legal channels.
        </Section>

        <Section title="15. Audio Fingerprinting and Analysis">
          When you upload audio content, IndieThis automatically generates acoustic fingerprints and analyzes audio features (BPM, key, energy, danceability, and other characteristics). This data is used for platform features including the explore page radar filter, quality ranking, collab matching, and DJ mix track identification. Audio fingerprints and features are stored as part of your content data and deleted when you delete your content.
        </Section>

        <Section title="16. Prohibited Conduct">
          You may not: use the Platform to distribute malware or harmful content; create fake accounts or inflate metrics artificially; harass, threaten, or abuse other users; upload content that is illegal, obscene, or promotes violence; reverse engineer or attempt to access the Platform&apos;s source code; use automated tools to scrape content or manipulate Platform features; resell or sublicense Platform access; impersonate other artists or misrepresent your identity.
        </Section>

        <Section title="17. Termination">
          We reserve the right to suspend or terminate your account for violation of these terms, fraudulent activity, or conduct that harms the Platform or its users. Upon termination, your public page will be taken offline. Your uploaded content remains accessible for 30 days to allow you to download it. After 30 days, content may be permanently deleted. Active subscriptions will be cancelled and no refund will be issued for the remaining period. Completed transactions (sales, purchases, licensing) survive termination.
        </Section>

        <Section title="18. Limitation of Liability">
          IndieThis is provided "as-is" without warranties of any kind. We are not liable for: lost revenue, data loss, service interruptions, AI output quality, third-party service failures (Stripe, Printful, Brevo, etc.), or any indirect, incidental, or consequential damages. Our total liability to you for any claim shall not exceed the amount you paid to IndieThis in the 12 months preceding the claim.
        </Section>

        <Section title="19. Dispute Resolution">
          Any disputes arising from these terms shall be resolved through binding arbitration in Cook County, Illinois under the rules of the American Arbitration Association. You waive any right to participate in a class action. Small claims court actions are exempt from this arbitration requirement.
        </Section>

        <Section title="20. Changes to Terms">
          We may update these terms at any time. Material changes will be communicated via email and in-app notification at least 30 days before taking effect. Continued use of the Platform after changes take effect constitutes acceptance of the updated terms.
        </Section>

        <Section title="21. Contact">
          For questions about these terms, contact us at{" "}
          <a href="mailto:info@indiethis.com" style={{ color: "#D4A843", textDecoration: "none" }}>
            info@indiethis.com
          </a>
          .<br /><br />
          Clear Ear Corp<br />
          Chicago, Illinois
        </Section>
      </main>

      {/* Footer */}
      <footer style={{ borderTop: "1px solid rgba(255,255,255,0.04)", padding: "20px 24px" }}>
        <div
          style={{
            maxWidth: 760,
            margin: "0 auto",
            display: "flex",
            flexWrap: "wrap",
            alignItems: "center",
            justifyContent: "space-between",
            gap: 12,
            fontSize: 12,
            color: "#444",
          }}
        >
          <span>© 2026 Clear Ear Corp</span>
          <div style={{ display: "flex", gap: 20 }}>
            <Link href="/terms" style={{ color: "#D4A843", textDecoration: "none" }}>Terms</Link>
            <Link href="/privacy" style={{ color: "#444", textDecoration: "none" }}>Privacy</Link>
            <a href="mailto:info@indiethis.com" style={{ color: "#444", textDecoration: "none" }}>
              info@indiethis.com
            </a>
          </div>
        </div>
      </footer>
    </div>
  );
}
